export const features = [
  {
    id: "font-size",
    type: "stepper",
    cssVar: "--equally-font-scale",
    unit: "",
    min: 0.8,
    max: 2,
    step: 0.1,
    default: 1,
    format: (value) => `${Math.round(value * 100)}%`,
  },
  {
    id: "line-height",
    type: "stepper",
    cssVar: "--equally-line-height",
    unit: "",
    min: 1,
    max: 2.5,
    step: 0.1,
    default: 1,
    format: (value) => value.toFixed(1),
  },
  {
    id: "letter-spacing",
    type: "stepper",
    cssVar: "--equally-letter-spacing",
    unit: "px",
    min: 0,
    max: 5,
    step: 0.5,
    default: 0,
    format: (value) => `${value}px`,
  },
  {
    id: "contrast",
    type: "toggle",
    filter: "contrast(1.5)",
    default: false,
  },
  {
    id: "greyscale",
    type: "toggle",
    filter: "grayscale(1)",
    default: false,
  },
  {
    id: "dyslexic",
    type: "toggle",
    className: "equally-dyslexic",
    default: false,
  },
  {
    id: "reduce-motion",
    type: "toggle",
    className: "equally-reduce-motion",
    default: false,
  },
  {
    id: "readable",
    type: "toggle",
    className: "equally-readable",
    default: false,
  },
  {
    id: "big-cursor",
    type: "toggle",
    className: "equally-big-cursor",
    default: false,
  },
  {
    id: "reading-guide",
    type: "toggle",
    className: "equally-reading-guide-active",
    default: false,
  },
  {
    id: "reading-mask",
    type: "toggle",
    className: "equally-reading-mask-active",
    default: false,
  },
];
